[window]
opacity = 0.75

[window.padding]
x = 0
y = 0

[font]
size = 13

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[colors.normal]
black = "0x1b1d2b"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0x828bb8"
yellow = "0xffc777"

[colors.bright]
black = "0x444a73"
blue = "0x82aaff"
cyan = "0x86e1fc"
green = "0xc3e88d"
magenta = "0xc099ff"
red = "0xff757f"
white = "0xc8d3f5"
yellow = "0xffc777"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc8d3f5"

[[colors.indexed_colors]]
color = "0xff966c"
index = 16

[[colors.indexed_colors]]
color = "0xc53b53"
index = 17
